# Generated by Django 4.2.6 on 2023-10-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.interest'),
        ),
    ]
