# Generated by Django 4.2.6 on 2023-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interest_remove_customuser_interest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
