# Generated by Django 4.2.6 on 2023-10-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_location_customuser_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.image'),
        ),
    ]
