# Generated by Django 4.2.6 on 2023-10-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_image_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejected',
            field=models.ManyToManyField(to='accounts.rejectedcards'),
        ),
    ]
