# Generated by Django 4.2.6 on 2023-10-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rejectedcards_customuser_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(to='accounts.likedcards'),
        ),
    ]
