# Generated by Django 4.2.6 on 2023-10-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_likedcards_customuser_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='likedyou',
            field=models.ManyToManyField(to='accounts.likedyou'),
        ),
    ]
