# Generated by Django 4.2.6 on 2023-10-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_likedyou_customuser_likedyou'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='matches',
            field=models.ManyToManyField(to='accounts.matches'),
        ),
    ]
